rnkizw/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='startseite'),
    path('impressum_und_datenschutz/', views.impressum_und_datenschutz, name='impressum_und_datenschutz')
]

rnkizw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rnkizw.dashboard.urls')),
]

rnkizw/dashboard/models.py
from django.db import models


class Impfzentrum(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=64)
    adresse = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Impfstoff(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Verfügbarkeit(models.Model):
    impfzentrum = models.ForeignKey(Impfzentrum, on_delete=models.CASCADE)
    impfstoff = models.ForeignKey(Impfstoff, on_delete=models.CASCADE)
    menge = models.IntegerField(default=0)
    aktualisiert = models.DateTimeField('Letzte Aktualisierung', auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['impfzentrum', 'impfstoff'], name='unique_verfügbarkeit')
        ]

    def __str__(self):
        return f'{self.menge} {self.impfstoff} in {self.impfzentrum} gesehen am {self.aktualisiert:%Y-%m-%d um %H:%M}'

rnkizw/dashboard/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render

from rnkizw import settings
from rnkizw.dashboard.models import Impfstoff, Impfzentrum


def index(request):
    impfstoffe = Impfstoff.objects.all().order_by('id')
    impfzentren = Impfzentrum.objects.all().order_by('id')

    zeilen = []
    for impfzentrum in impfzentren:
        mengen = []
        for impfstoff in impfstoffe:
            try:
                verfügbarkeit = impfzentrum.verfügbarkeit_set.get(impfstoff=impfstoff)
            except ObjectDoesNotExist:
                mengen.append(0)
            else:
                mengen.append(verfügbarkeit.menge)

        max_termine = max(menge for menge in mengen)
        verfügbarkeiten = impfzentrum.verfügbarkeit_set.all()

        zeilen.append({
            'impfzentrum': impfzentrum,
            'mengen': mengen,
            'status': 'freie_termine' if max_termine >= 5 else 'wenige_termine' if max_termine > 0 else 'keine_termine',
            'aktualisiert': min(
                verfügbarkeit.aktualisiert for verfügbarkeit in impfzentrum.verfügbarkeit_set.all()
            ) if verfügbarkeiten else '',
        })

    return render(request, 'dashboard/index.html', {
        'impfstoffe': impfstoffe,
        'zeilen': zeilen,
    })


def impressum_und_datenschutz(request):
    return render(request, 'dashboard/impressum_und_datenschutz.html', {
        'postadresse': settings.IMPRESSUM_POSTADRESSE,
        'email': settings.IMPRESSUM_EMAILADRESSE,
    })

rnkizw/dashboard/templates/dashboard/basis.html
{% load static %}

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "dashboard/style.css" %}">
    <title>Impfterminübersicht Rhein-Neckar</title>
</head>
<body>
    <div id="Kopfzeile"><h1>
        {% block titel %}<a href="{% url 'dashboard:startseite' %}">Impfterminübersicht Rhein-Neckar</a>{% endblock %}
    </h1></div>
    <div id="Inhalt">
        {% block Inhalt %}
        {% endblock %}
    </div>
    <div id="Fußzeile">
        <ul>
            <li><a href="{% url 'dashboard:impressum_und_datenschutz' %}">Impressum, Datenschutz und Lizenzen</a></li>
        </ul>
    </div>
</body>
</html>

rnkizw/dashboard/templates/dashboard/impressum_und_datenschutz.html
{% extends "dashboard/basis.html" %}

{% block titel %}{{ block.super }} - Startseite{% endblock %}

{% block Inhalt %}

    <h2>Impressum</h2>

    <address>
    {{ postadresse | linebreaks }}
    </address>

    <h3>Elektronische Kontaktadresse</h3>
    <address>{{ email }}</address>
    <p>Bitte signieren und verschlüsseln Sie die Kommunikation!</p>

    <h2>Datenschutz</h2>
    <p>
    Zur Fehlersuche und Gefahrenabwehr werden die Zugriffe mit den IP-Adressen der Zugreifenden protokolliert.
    Ansonsten werden keine Benutzerdaten erhoben.
    </p>
    <p>
    Verantwortlich:
    </p>
    <address>
    {{ postadresse | linebreaksbr }}
    </address>
    <address>
    Email: {{ email }}
    </address>

    <h2>Lizenzen</h2>
    <p>
    Die Software welche diese Übersicht generiert unterliegt der GNU Affero General Public License 3 oder später.
    Der komplette Lizenztext kann unter <a href="https://www.gnu.org/licenses/agpl-3.0.html">https://www.gnu.org/licenses/agpl-3.0.html</a> eingesehen werden.
    Der Quelltext der Software ist auf <a href="https://codeberg.org/Marix/rnkizw">https://codeberg.org/Marix/rnkizw</a> zu finden.
    </p>
{% endblock %}

rnkizw/dashboard/templates/dashboard/index.html
{% extends "dashboard/basis.html" %}

{% block titel %}{{ block.super }} - Startseite{% endblock %}

{% block Inhalt %}

<p>
Die Tabelle zeigt die Anzahl der, zum Zeitpunkt der letzten Aktualisierung, auf <a href="https://c19.rhein-neckar-kreis.de/impftermin">der Impfterminbuchungsseite des Rhein-Neckar-Kreises</a> verfügbaren Terminslots für Impfungen mit den jeweiligen Impfstoffen.
Diese Tabelle ist <em>kein</em> Angebot des Rhein-Neckar-Kreises, sondern eine private Initiative.
<p>

<table>
    <tr>
        <th>Impfzentrum</th>
        {% for impfstoff in impfstoffe %}
            <th>{{ impfstoff }}</th>
        {% endfor %}
        <th>Letzte Aktualisierung</th>
    </tr>
    {% for zeile in zeilen %}
        <tr class="{{ zeile.status }}">
            <td class="zeilentitel">
                {{ zeile.impfzentrum }}
            </td>
            {% for menge in zeile.mengen %}
                <td class="menge">
                    {{ menge }}
                </td>
            {% endfor %}
            <td class="aktualisierung">{{ zeile.aktualisiert }}</td>
        </tr>
    {% endfor %}
</table>

<p>
Termine können auf der Seite <a href="https://c19.rhein-neckar-kreis.de/impftermin">https://c19.rhein-neckar-kreis.de/impftermin</a> des Rhein-Neckar-Kreises gebucht werden.
</p>
<p>
Die Anzahl der verfügbaren Termine kann sich seit der letzten Aktualisierung geändert haben.<br>
Der gleiche Termin kann für mehrere Impfstoffe angeboten werden kann.
Deshalb heißen je fünf verfügbare Termine in einem Zentrum nicht, dass 15 Termine verfügbar sind.
Es muss auch nicht heißen, dass fünf Termine mit einem bestimmten Impfstoff gebucht werden können.
Es heißt lediglich, dass für jeden der Impfstoffe, fünf buchbare Slots verfügbar sind.
</p>

{% endblock %}